datamodule:
  zarr_path: data/irp_rope.zarr
  name: traj_occu_rechunk_action
  zarr_cache_size: null
  # dataloader
  dataloader_params:
    batch_size: 16
    num_workers: 8
    prefetch_factor: 4
    pin_memory: False
  # async cpu to gpu transfer
  async_device: null
  # sample
  action_sigma: 0.125
  random_init: False
  # image
  distance: False
  pix_per_m: 60.34
  direction: False
  size:
    train: 10000
    val: 10000
    test: 10000
model:
  action_sigma: null
  learning_rate: 0.001
  weight_decay: 0.000001
  loss: 'bce'
checkpoint_callback:
  save_top_k: 10
  every_n_epochs: 1
vis_callback:
  input_key: 'target_trajectory'
  num_samples: 16
  seed: 0
trainer:
  gpus: [0]
  check_val_every_n_epoch: 1
  val_check_interval: 1.0
logger:
  offline: True
  name: null
  tags: []
