datamodule:
  data_dir: data/tracking
  train_split: 0.95
  split_seed: 0
  batch_size: 4
  num_workers: 4
  sigma: 2.0
  imgaug_cfg:
    apply_prob: 0.5
    
    crop_size: [400, 400]
    max_shift: 0.4
    crop_sampling: hybrid

    cropratio: 0.4

    rotation: 25
    rotratio: 0.4

    scale_jitter_lo: 0.5
    scale_jitter_up: 1.25

    mirror: True

    clahe: True
    claheratio: 0.1
    histeq: True
    histeqratio: 0.1

    sharpen: True
    sharpenratio: 0.3
    edge: False
    emboss:
      alpha: [0.0, 1.0]
      strength: [0.5, 1.5]
      embossratio: 0.1

    # sigmoid: True
    # sigmoidratio: 0.1

    # gamma: True
    # gammaratio: 0.1

    # linear: True
    # linearratio: 0.1

    gaussian_noise: True

model:
  learning_rate: 0.0005
  weight_decay: 0.0001
  upsample: True
checkpoint_callback:
  save_top_k: 10
  every_n_epochs: 1
vis_callback:
  num_samples: 8
  seed: 0
trainer:
  gpus: [0]
  check_val_every_n_epoch: 1
  val_check_interval: 1.0
logger:
  offline: True
  name: null
  tags: []
